algoritmo "semnome"
// Função :
// Autor :
// Data : 03/04/2022
// Seção de Declarações 
var
   reais,dolar: real
inicio
      escreval("Quantos Reais eu tenho?: ")
      leia(reais)
      
      escreval("==============================")
      escreval("Iniciando a compra do dolar")
      escreval("CONVERTENDO")
      
      dolar <- reais / 4,66
      
      escreval("Você consegue comprar o toal de: ",dolar)
      escreval("===================================")
fimalgoritmo
